### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by lordcrekit** [lordcrekit/MI-449-SS17-740-js-server-intro-jtrO3q#1]
@egillespie Can you take a look at this? It's [hosted here](https://normanwi-kappab1hhmo94jtro3q.herokuapp.com/) and meets the following criteria:

- [x] At every URL, you respond with HTML, starting with an `h1` element (though for this project, it doesn't have to be a complete HTML page)
- [x] When a user visits `/`, they see a greeting
- [x] When a user visits `/random-joke`, they see one of at least three [knock-knock jokes](http://www.short-funny.com/best-knock-jokes.php) (`Math.random()` may be useful 😉)
- [x] When a user visits `/cuteness`, they see a picture of a cute animal (I'm sure you can find one on the Internet 😛)
- [x] At every other URL, display an error page (if you want to make it funny, see [these examples](http://www.hongkiat.com/blog/60-really-cool-and-creative-error-404-pages/) for inspiration)
- [x] The error page includes the requested URL, similar to [Google's error page](http://google.com/secret-plan-to-take-over-the-world)
- [x] Every page that is _not_ the homepage (`/`) contains a link to it

Used express because easier

**Comment by egillespie** [comment]
14 files vs. 2 is easier? 😝 The results look pretty good. I won't get too into the weeds with feedback about your Express code, but will touch on the stuff you'll be learning in this course.

### Make sure your JavaScript passes linting

Linted code has a lower likelihood of bugs and in a team environment (which most software development environments are), it makes everyone's code consistent and easy to read.

Here's a list of errors for `index.js`:

```
  index.js:6:24: Use path.join() or path.resolve() instead of + to create paths.
  index.js:9:18: Use path.join() or path.resolve() instead of + to create paths.
  index.js:12:22: Missing space before function parentheses.
  index.js:13:5: Expected indentation of 2 spaces but found 4.
  index.js:17:33: Missing space before function parentheses.
  index.js:18:65: Infix operators must be spaced.
  index.js:25:22: Missing space before function parentheses.
  index.js:26:25: Expected consistent spacing
  index.js:29:37: Missing space before function parentheses.
  index.js:30:5: Expected indentation of 2 spaces but found 4.
```

### Knock-knock jokes plz

In programming jobs, teams will commonly be given AC (acceptance criteria) for software changes they must implement. After teammates perform code reviews, there's also usually a quality and/or business analyst who will review the resulting software and sign off on the AC before it can be deployed to a production environment.

We've structured our projects and review process to help prepare you for those jobs. Right now I have my business analyst hat on 🎩  and don't see any knock-knock jokes and I'm sad because it took me half an hour of Googling to find a site with jokes that match just the right kind of humor for our product. Can I see some of them on this site?

### `views` is already the default location of templates

```js
app.set('views', __dirname + '/views')
```

This line isn't needed since `views` is already the default location for templates in Express.

### `.env` is not needed

You can safely remove this file since it's empty and you're not referencing it anywhere. Leaving it around could mislead someone who is familiar with `dotenv` or a similar package to put things in there only to find the file's not actually being used.

---

After you’ve made your changes and pushed them to GitHub and your hosted site, give it a once-over to make sure it looks right, then comment back here and I’ll take another look.

Thanks! 🍰

**Comment by lordcrekit** [comment]
### On fixes
Fixed.
### On 'easier'
Okay maybe its not easier... but!
- ejs makes templating html way better than having to write it out in the javascript.
- This way you can't get to random-joke through `BASEURL/askljfgjkdsaghjkdslagh/random-joke`

**Comment by egillespie** [comment]
I think it's awesome that you're going above and beyond the tech specs for many of your projects, I was just pulling your chain about Express being easier. 😉⛓

These changes look great! :shipit:
